#+TITLE: Org mode config
#+DESCRIPTION: Configuration for org-mode
#+LANGUAGE: en
#+PROPERTY: header-args    :results silent
Enable lexical binding (needed for some of the org-roam config). *This must be at the top of the file.*
#+BEGIN_SRC emacs-lisp
;; -*- lexical-binding: t; -*-
#+END_SRC

* General

Save all org buffers periodically to reduce conflicts between desktop and orgzly on mobile.
#+BEGIN_SRC emacs-lisp
(run-with-idle-timer 60 t 'org-save-all-org-buffers)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq org-return-follows-link t)
#+END_SRC

Most of this is from [[https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html][this]] guide:

Set the org directory and method for getting the full path to an org file from its name.
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/Dropbox/org/gtd")

(defun org-file-path (filename)
  "Return the absolute address of an org file, given its relative name."
  (concat (file-name-as-directory org-directory) filename))
#+END_SRC

Prettier bullets
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :init
    (add-hook 'org-mode-hook 'org-bullets-mode))
#+END_SRC

Increase list indentation
#+BEGIN_SRC emacs-lisp
(setq org-list-indent-offset 2)
#+END_SRC

Set a sequence for list bullet symbols.
#+BEGIN_SRC emacs-lisp
(setq org-list-demote-modify-bullet '(("+" . "-") ("-" . "+") ("*" . "+")))
#+END_SRC

Color the TODO states.
#+BEGIN_SRC emacs-lisp
(setq org-todo-keyword-faces
'(("WAITING" . (:foreground "darkorange" :background "lightyellow" :weight bold :box t))
	("TODO" . (:foreground "darkblue" :background "lightblue" :weight bold :box t))
	("PROJECT" . (:foreground "white"))
	("NEXT" . (:foreground "darkblue" :background "lightblue" :weight bold :box t))))
#+END_SRC

* Fonts
Enable changing font face per buffer. From https://www.emacswiki.org/emacs/FacesPerBuffer.

ETBookOT font is installed from https://github.com/edwardtufte/et-book (by downloading the .otf files in =et-book-ligatures-enabled= and putting them in =~/.local/share/fonts= and running =fc-cache -f -v=). (Font name obtained from =fc-list=.)
#+BEGIN_SRC emacs-lisp
;; Use variable width font faces in current buffer
(defun my-buffer-face-mode-variable ()
  "Set font to a variable width (proportional) fonts in current buffer"
  (interactive)
  (setq buffer-face-mode-face '(:family "Source Sans Pro" :height 140))
  (buffer-face-mode))

 ;; Use monospaced font faces in current buffer
 (defun my-buffer-face-mode-fixed ()
   "Sets a fixed width (monospace) font in current buffer"
   (interactive)
   (setq buffer-face-mode-face '(:family "Consolas" :weight 'light))
   (buffer-face-mode))
#+END_SRC

Use the variable font for org buffers by default.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'my-buffer-face-mode-variable)
#+END_SRC

But use monospace font in code blocks and tables.  From https://github.com/jparcill/emacs_config/blob/master/config.el
#+BEGIN_SRC emacs-lisp
(set-face-attribute 'org-table nil :inherit 'fixed-pitch)
(set-face-attribute 'org-block nil :inherit 'fixed-pitch)
(set-face-attribute 'org-table nil  :inherit 'fixed-pitch)
(set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
(set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
(set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
(set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
(set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
#+END_SRC

* Refiling
Set targets for refiling. Use =C-c C-w= to refile. This determines what options you're prompted with. Includes everything in all the agenda files, plus the someday file and various list files.
#+BEGIN_SRC emacs-lisp
(setq org-refile-targets '((org-agenda-files :maxlevel . 3)
                           ("someday.org" :level . 1)
			   ("l-media.org" :maxlevel . 2)
			   ("l-ideas.org" :maxlevel . 2)))
#+END_SRC

Include the file name in the outline path to allow refiling as a top-level heading.
#+BEGIN_SRC emacs-lisp
(setq org-refile-use-outline-path 'file)
(setq org-outline-path-complete-in-steps nil)
#+END_SRC

Create ids for links so they will work even if you move them across files.
#+BEGIN_SRC emacs-lisp
(setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id
      org-clone-delete-id t)
#+END_SRC

* Key bindings
#+BEGIN_SRC emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-cC" 'klk/open-calendar)
#+END_SRC

* Images
Make files start with inline images loaded, and add a hook to display them after executing a code block to display resulting graphs.
#+BEGIN_SRC emacs-lisp
(setq org-startup-with-inline-images t)
(add-hook 'org-babel-after-execute-hook 'org-display-inline-images 'append)
#+END_SRC

Set this to =nil= to allow customizing image preview size with something like:
=#ATTR_ORG: :width 200=
#+BEGIN_SRC emacs-lisp
(setq org-image-actual-width nil)
#+END_SRC

Scale up latex preview images.
#+BEGIN_SRC emacs-lisp
(setq org-format-latex-options (plist-put org-format-latex-options :scale 1.7))
(setq org-preview-latex-image-directory "/tmp/ltximg/")
(setq org-preview-latex-default-process 'imagemagick)
#+END_SRC

* Tasks

** General
Stop parent tasks from being marked as complete if they have incomplete children.
#+BEGIN_SRC emacs-lisp
(setq org-enforce-todo-dependencies t)
(setq org-agenda-dim-blocked-tasks nil)
#+END_SRC

Set the =TODO= states.
#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords '((sequence
			   "TODO(t!)"
			   "NEXT(n)"
			   "WAITING(w@)"
			   "PROJECT(p)"
			   "INP(i!)"
			   "|"
			   "DONE(d)"
			   "CANCELLED(c@)"
			   "NOTE(e)"
			   )
			   ))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq org-agenda-skip-unavailable-files t)
#+END_SRC

[[https://orgmode.org/worg/org-contrib/org-checklist.html][org-checklist]] supports recurring checklists
#+BEGIN_SRC emacs-lisp
;(use-package org-checklist)
#+END_SRC

** Archiving
   Archive to =archive.org= under a tree heading with the name of the origin file.
#+BEGIN_SRC emacs-lisp
  (setq org-archive-location
        (concat (org-file-path "archive.org") "::* From %s"))
#+END_SRC

** Logging
 Log state changes in a drawer, not in the task content.
 #+BEGIN_SRC emacs-lisp
 (setq org-log-state-notes-into-drawer t)
 #+END_SRC

 This will log a CLOSED timestamp when an item is marked as done. This is consistent with what orgzly does, and seems to show up in the agenda much like state change logs, except it makes archived items show up as well.
 #+BEGIN_SRC emacs-lisp
 (setq org-log-done 'time)
 #+END_SRC

** Capture
#+BEGIN_SRC emacs-lisp
(setq org-capture-templates `(
			("t" "Tasks")
			("tt" "Todo"
			 entry (file ,(org-file-path "inbox.org"))
			 "* TODO %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n  %i\n")
			("tn" "Next task"
			 entry (file ,(org-file-path "inbox.org"))
			 "* NEXT %?\n:PROPERTIES:\n:CREATED: %U\n:END:\n  %i\n")
			("ts" "Scheduled Todo"
			 entry (file ,(org-file-path "inbox.org"))
			 "* TODO %? \nSCHEDULED: %^{scheduled}t\n:PROPERTIES:\n:CREATED: %U\n:END:\n  %i\n")
			("td" "Todo with Deadline"
			 entry (file ,(org-file-path "inbox.org"))
			 "* TODO %? \nDEADLINE: %^{deadline}t\n:PROPERTIES:\n:CREATED: %U\n:END:\n  %i\n")
			("n" "Notes")
			("ng" "Gardening related"
			 entry (file+headline ,(org-file-path "p-garden.org") "Notes")
			 "* %^{title}\n:PROPERTIES:\n:CREATED: %U\n:END:\n%?")
			("nh" "Health related"
			 entry (file+headline ,(org-file-path "p-health.org") "Notes")
			 "* %^{title}\n:PROPERTIES:\n:CREATED: %U\n:END:\n\n%?")
			("nf" "Finance related"
			 entry (file+headline ,(org-file-path "p-financial.org") "Notes")
			 "* %^{title}\n:PROPERTIES:\n:CREATED: %U\n:END:\n%?")
			("p" "Project"
			 entry (file ,(org-file-path "gtd.org"))
			 "* PROJECT %^{name} \n:PROPERTIES:\n:CREATED: %U\n:PROJECT: %\\1\n:OUTCOME: %?\n:END:\n")
			("T" "Troubleshooting"
			 entry (file ,(org-file-path "troubleshooting.org"))
			 "* %^{problem} \n:PROPERTIES:\n:CREATED: %U\n:END:\n** Solution\n%^{solution}\n** Details\n%?")
			("w" "Weekly" entry
			 (file ,(org-file-path "journal/weekly2021.org"))
			 "** Week %^{week number}
[[file:~/Dropbox/org/roam/dailies/%^{start of week (yyyymmdd).org}]]
,*** Goals / priorities :goals:
- %?
,*** Review :weekly:
,*** Key Ideas :keyideas:\n")
			("m" "Monthly" entry
			 (file ,(org-file-path "journal/weekly2021.org"))
			 "* %^{month}
,** %\\1 Goals / priorities :goals:
- %?
,** %\\1 Review :monthly:
,** %\\1 Key Ideas :monthlykeyideas:
,** %\\1 Highlights :highlights:\n" :empty-lines 1)
			("a" "Accomplishments" entry
			 (file+datetree ,(org-file-path "accomplishments.org"))
			 "* %?")
			("D" "Daily" entry
			 (file+datetree ,(org-file-path "journal/daily.org"))
			 "* NOTE %? \nSCHEDULED: %t\nCLOSED: %t")
			("N" "Daily Note" entry
			 (file+datetree ,(org-file-path "journal/daily.org"))
			 "* NOTE %? \nSCHEDULED: %^{Date}t\nCLOSED: %^{Same date again}t")
			))
#+END_SRC

** Agenda
Make agenda full screen.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-agenda-finalize-hook (lambda () (delete-other-windows)))
#+END_SRC

Some agenda view tweaks.
#+BEGIN_SRC emacs-lisp
(setq org-agenda-skip-scheduled-if-done t)
(setq org-agenda-skip-deadline-if-done t)
(setq org-agenda-include-deadlines t)
(setq org-agenda-start-with-log-mode t)
(setq org-deadline-warning-days 7)
#+END_SRC

Set files to be included in the agenda. Includes archive because I like to see old completed tasks in the agenda, and also =daily.org= because I want to show my one-line daily summaries in the agenda.
#+BEGIN_SRC emacs-lisp
(setq org-agenda-files `(,(org-file-path "inbox.org")
			 ,(org-file-path "mobile inbox.org")
			 ,(org-file-path "gtd.org")
			 ,(org-file-path "work.org")
			 ,(org-file-path "recurring.org")
			 ,(org-file-path "archive.org")
			 ,(org-file-path "p-financial.org")
			 ,(org-file-path "p-health.org")
			 ,(org-file-path "p-garden.org")
			 ,(org-file-path "journal/daily.org")))
#+END_SRC

Super Agenda
#+BEGIN_SRC emacs-lisp
(use-package org-super-agenda
  :config
  (org-super-agenda-mode t))
(require 'org-habit)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-custom-commands
	(list
	 (quote
	  ("h" "Hotlist"
	   ((tags-todo "DEADLINE<\"<+0d>\""
		       ((org-agenda-overriding-header "OVERDUE")))
	    (tags-todo "DEADLINE>=\"<+0d>\"+DEADLINE<=\"<+1w>\""
		       ((org-agenda-overriding-header "DUE IN NEXT 7 DAYS")))
	    (tags-todo "DEADLINE=\"\"+PRIORITY={A}|DEADLINE>\"<+1w>\"+PRIORITY={A}"
		       ((org-agenda-overriding-header "HIGH PRIORITY")))
	    (tags-todo "DEADLINE=\"\"+FLAGGED|DEADLINE>\"<+1w>\"+FLAGGED"
		       ((org-agenda-overriding-header "FLAGGED")
			(org-agenda-skip-function
			 '(org-agenda-skip-entry-when-regexp-matches))
			(org-agenda-skip-regexp "\\[#A\\]"))))
	   ((org-agenda-todo-ignore-scheduled 'future)
	    (org-agenda-sorting-strategy '(deadline-up)))))
	 (quote
	  ("x" "Daily Agenda"
	   (
	    (tags-todo "+PRIORITY={A}"
		       ((org-agenda-overriding-header "High Priority Tasks")))
	    (
	     agenda "" ((org-agenda-span 'day)
			(org-agenda-log-mode-items '(closed clock state))
			(org-agenda-prefix-format "  %?-12t% s")
					  ; (org-agenda-compact-blocks t)
			(org-super-agenda-groups
			 '(
			   (:name "⏰ Calendar" :time-grid t)
			   (:name "⚠ Overdue!" :deadline past)
			   (:name "⚠ Overdue!" :and (:scheduled past :not (:habit t)))
			   (:auto-property "Project")
			   (:auto-category)
			   (:name "Misc. Scheduled" :and (:scheduled today :not (:habit t)))
			   (:name "Due" :and (:deadline today :not (:habit t)))
			   (:name "⭐ Next" :todo "NEXT")
			   (:name "⭐ Important" :priority "A")
			   ;(:name "📌 Routines" :and (:habit t :category "recurring" :tag "habit"))
			   (:name "📌 Chores" :and (:habit t :category "recurring" :tag "chore"))
			   ))
			))
	    ;; (todo "NEXT"
	    ;; 	((org-agenda-overriding-header "Next Tasks")
	    ;; 	 (org-super-agenda-groups '((:auto-property "Project")))
	    ;; 	 ))
	    )))
	 (quote
	  ("U" "Unscheduled"
	   ((todo ""
		  ((org-agenda-overriding-header "Unscheduled Tasks")
		   (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'todo '("PROJECT"))))))
	   ((org-agenda-todo-ignore-scheduled 'future)
	    (org-agenda-sorting-strategy '(deadline-up)))))
	 (quote("N" "Next tasks" todo "NEXT"
		((org-agenda-overriding-header "Next Tasks")
		   (org-super-agenda-groups '((:auto-property "Project") (:auto-category)))
		   ))
		)
	 (quote("p" "Project tasks" todo ""
		(
		 (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo '("PROJECT")))
		 (org-super-agenda-groups '((:auto-property "Project" :not (:todo "PROJECT")) (:discard (:anything t))))
		 )
		))
	 (quote
	  ("n" "Notes"
	   (
	    (agenda "" ((org-agenda-span 'week)
			(org-agenda-log-mode-items '(closed clock state))
			(org-agenda-prefix-format "  %?-12t% s")
					  ; (org-agenda-compact-blocks t)
			(org-super-agenda-groups
			 '(
			   (:name "Daily Summary" :and (:time-grid t :tag "daily"))
			   (:discard (:anything t))
			   ))
			)))))
	 )
	)
#+END_SRC

* Journal

*** deft
Deft is good for searching through files in a directory, like the journal directory.
=deft-parse-title= override is from https://github.com/jrblevin/deft/issues/75 so the title isn't just ":PROPERTIES:" with org-roam V2.
#+BEGIN_SRC emacs-lisp
(use-package deft
  :bind ("C-c d" . deft)
  :bind ("C-c D" . deft-find-file)
  :commands (deft)
  :config
  (setq deft-default-extension "org"
	deft-extensions '("org")
	deft-directory "~/Dropbox/org/roam"
	deft-recursive t
	deft-strip-summary-regexp ":PROPERTIES:\n\\(.+\n\\)+:END:\n\\(#\\+.+\n\\)*\\(- .+::.+\n\\)?"
	deft-use-filename-as-title nil
	deft-file-naming-rules '((noslash . "-")
				 (nospace . "-")
				 (case-fn . downcase))
	deft-text-mode 'org-mode)
  )
(advice-add 'deft-parse-title :override
    (lambda (file contents)
      (if deft-use-filename-as-title
	  (deft-base-filename file)
	(let* ((case-fold-search 't)
	       (begin (string-match "title: " contents))
	       (end-of-begin (match-end 0))
	       (end (string-match "\n" contents begin)))
	  (if begin
	      (substring contents end-of-begin end)
	    (format "%s" file))))))
#+END_SRC

*** ripgrep
An alternative to =deft=, using =ripgrep=. Nice in that it actually shows the matches, not just the beginning of the file containing a match.
Config based on https://renatgalimov.github.io/org-basb-code/.
#+BEGIN_SRC emacs-lisp
(use-package helm-rg
  :init
  (defun helm-rg-roam-directory (&optional query)
    "Search with rg in your roam directory, QUERY."
    (interactive)
    (let ((helm-rg-default-directory "~/Dropbox/org/roam"))
      (helm-rg query nil)))
  :bind (("C-c n R" . helm-rg-roam-directory)))
#+END_SRC

*** random note
Random note, for looking at a random past entry.
#+BEGIN_SRC emacs-lisp
(use-package org-randomnote
	:bind ("C-c r" . org-randomnote)
	:config
	(setq org-randomnote-candidates (directory-files "~/Dropbox/org/roam/dailies" t "^[0-9]+.org$" t))
	(setq org-randomnote-open-behavior 'indirect-buffer)
	)
#+END_SRC

* Visual

Use syntax highlighting in source blocks while editing.

#+BEGIN_SRC emacs-lisp
  (setq org-src-fontify-natively t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (setq org-src-preserve-indentation t)
#+END_SRC

Hide emphasis markers like *,/,=

#+BEGIN_SRC emacs-lisp
(setq org-hide-emphasis-markers t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq org-hide-leading-stars t)
#+END_SRC

Load images inline.

#+BEGIN_SRC emacs-lisp
(setq org-startup-with-inline-images t)
#+END_SRC

This changes the context settings for sparse subtrees so that it will show the content of a heading matching the tag.
#+BEGIN_SRC emacs-lisp
(push '(tags-tree . local) org-show-context-detail)
#+END_SRC

Use variable font sizes for headings
#+BEGIN_SRC emacs-lisp
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.75))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.5))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.25))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.1))))
)
#+END_SRC

* Code
** General
Make TAB act as if it were issued in a buffer of the language's major mode.
#+BEGIN_SRC emacs-lisp
  (setq org-src-tab-acts-natively t)
#+END_SRC

When editing a code snippet, use the current window rather than popping open a
new one (which shows the same information).
#+BEGIN_SRC emacs-lisp
  (setq org-src-window-setup 'current-window)
#+END_SRC

Additional shortcuts for inserting code blocks.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
	       '("r" "#+BEGIN_SRC R \n?\n#+END_SRC"))
#+END_SRC

* Roam
#+BEGIN_SRC emacs-lisp
(use-package org-roam
  ;; the repo has org-roam-dailies.el in an extensions folder; force it to be included
  :straight (org-roam :type git :flavor melpa :host github :repo "org-roam/org-roam"
		      :files ("*.el" "extensions/*.el"))
  :demand t ; force this to be loaded
  :custom
  (org-roam-directory "~/Dropbox/org/roam")
  :init
  (setq org-roam-v2-ack t)
  :config
  (org-roam-db-autosync-mode)
  (define-key org-roam-mode-map [mouse-1] #'org-roam-buffer-visit-thing)
  ;; Keep backlink buffer as side window like v1
  ;; (add-to-list 'display-buffer-alist
  ;;              '("\\*org-roam\\*"
  ;;                 (display-buffer-in-direction)
  ;;                 (direction . right)
  ;;                 (window-width . 0.33)
  ;;                 (window-height . fit-window-to-buffer)))
  (setq org-roam-capture-templates
        '(("d" "default" plain
           "%?"
           :if-new (file+head
		    "%<%Y%m%d%H%M%S>-${slug}"
		    "#+title: ${title}\n#+startup: latexpreview\n#+filetags: \n")
           :unnarrowed t)
	  ("p" "person" plain
           "%?"
           :if-new (file+head
		    "%<%Y%m%d%H%M%S>-${slug}"
		    "#+title: ${title}\n#+startup: latexpreview\n#+filetags: :person: \n")
           :unnarrowed t)
	  ("e" "podcast episode" plain
           "Episode of %?"
           :if-new (file+head
		    "%<%Y%m%d%H%M%S>-${slug}"
		    "#+title: ${title}\n#+startup: latexpreview\n#+filetags: :podcast:episode:\n ")
           :unnarrowed t)
	  ("o" "organization" plain
           "%?"
           :if-new (file+head
		    "%<%Y%m%d%H%M%S>-${slug}"
		    "#+title: ${title}\n#+startup: latexpreview\n#+filetags: :organization: \n")
           :unnarrowed t)
	  ("r" "bibliography reference" plain "%?"
           :if-new
           (file+head "references/${citekey}.org" "#+title: ${title}\n")
	   :unnarrowed t)))
(setq org-roam-dailies-directory "dailies/")
(setq org-roam-dailies-capture-templates
      (quote (("d" "daily" plain
               "%?"
               :if-new (file+head
                        "%<%Y%m%d>.org"
                        "#+title: %<%Y-%m-%d (%A)>\n\n\n")
               :unnarrowed t))))
  #+END_SRC

  Handy config from https://systemcrafters.net/build-a-second-brain-in-emacs/5-org-roam-hacks/ to add roam files with the =Project= tag to the agenda list, so I can track TODOs within a project.

Add existing projects to agenda list on startup:
  #+BEGIN_SRC emacs-lisp
(defun my/org-roam-filter-by-tag (tag-name)
  (lambda (node)
    (member tag-name (org-roam-node-tags node))))

(defun my/org-roam-list-notes-by-tag (tag-name)
  (mapcar #'org-roam-node-file
          (seq-filter
           (my/org-roam-filter-by-tag tag-name)
           (org-roam-node-list))))

(defun my/org-roam-refresh-agenda-list ()
  (interactive)
  (setq org-agenda-files (append org-agenda-files (my/org-roam-list-notes-by-tag "project"))))

;; Build the agenda list the first time for the session
(my/org-roam-refresh-agenda-list)
#+END_SRC

And add new projects to agenda list after capture.
#+BEGIN_SRC emacs-lisp
(defun my/org-roam-project-finalize-hook ()
  "Adds the captured project file to `org-agenda-files' if the
capture was not aborted."
  ;; Remove the hook since it was added temporarily
  (remove-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

  ;; Add project file to the agenda list if the capture was confirmed
  (unless org-note-abort
    (with-current-buffer (org-capture-get :buffer)
      (add-to-list 'org-agenda-files (buffer-file-name)))))

(defun my/org-roam-find-project ()
  (interactive)
  ;; Add the project file to the agenda after capture is finished
  (add-hook 'org-capture-after-finalize-hook #'my/org-roam-project-finalize-hook)

  ;; Select a project file to open, creating it if necessary
  (org-roam-node-find
   nil
   nil
   (my/org-roam-filter-by-tag "project")
   :templates
   '(("p" "project" plain "* Goals\n\n%?\n\n* Tasks\n\n** TODO Add initial tasks\n\n"
      :if-new (file+head
	       "%<%Y%m%d%H%M%S>-${slug}"
	       "#+title: ${title}\n#+category: ${title}\n#+filetags: :project:")
      :unnarrowed t))))
#+END_SRC

Set key bindings and end =use-package= =org-roam= config.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c n p") #'my/org-roam-find-project)
:bind (("C-c j" . org-roam-dailies-goto-today)
       ("C-c t" . org-roam-dailies-goto-tomorrow)
       ("C-c y" . org-roam-dailies-goto-yesterday)
       ("C-c n d" . org-roam-dailies-goto-date)
       ("C-c n f" . org-roam-node-find)
       ("C-c n l" . org-roam-buffer-toggle)
       ("C-c n i" . org-roam-node-insert)
       ("C-c f" . org-roam-dailies-find-next-note)
       ("C-c b" . org-roam-dailies-find-previous-note)))
#+END_SRC

* Reference management

** pdf-tools
Better pdf interactions in Emacs.
#+BEGIN_SRC emacs-lisp
(use-package pdf-tools
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page)
  (add-hook 'pdf-tools-enabled-hook 'pdf-view-midnight-minor-mode)
  :custom
  (pdf-annot-activate-created-annotations t "automatically annotate highlights")
)
#+END_SRC

** bibtex
Set paths that will be used by multiple packages.
#+BEGIN_SRC emacs-lisp
(setq bib-files (directory-files "~/Dropbox/Zotero" t "^[A-Z|a-z].+.bib$")
      pdf-files-directory "~/Dropbox/papers/bibtex")
#+END_SRC

** helm-bibtex
Set up =helm-bibtex= to use the Zotero =.bib= file and store notes in the =org-roam= directory.
#+BEGIN_SRC emacs-lisp
(use-package helm-bibtex
  :config
  (require 'helm-config)
  (setq bibtex-completion-bibliography bib-files
        bibtex-completion-library-path pdf-files-directory
        bibtex-completion-pdf-field "File"
        bibtex-completion-notes-path org-roam-directory))
#+END_SRC

** org-ref
Manage references in org mode.
#+BEGIN_SRC emacs-lisp
(use-package org-ref
  :config
  (setq org-ref-completion-library 'org-ref-helm-cite
        org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex
        org-ref-default-bibliography bib-files
        org-ref-notes-directory org-roam-directory
        org-ref-notes-function 'orb-edit-notes)
  ;; Open pdfs in Emacs, not externally
  (defun my/org-ref-open-pdf-at-point ()
    "Open the pdf for bibtex key under point if it exists."
    (interactive)
    (let* ((results (org-ref-get-bibtex-key-and-file))
           (key (car results))
           (pdf-file (funcall org-ref-get-pdf-filename-function key)))
      (if (file-exists-p pdf-file)
          (find-file pdf-file)
	(message "No PDF found for %s" key))))

  (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
  )
#+END_SRC

** org-roam-bibtex
Integrate bibtex with =org-roam=.
#+BEGIN_SRC emacs-lisp
(use-package org-roam-bibtex
  :after (org-roam helm-bibtex)
  :bind (:map org-mode-map ("C-c n b" . orb-note-actions))
  :config
  (require 'org-ref) ; optional: if Org Ref is not loaded anywhere else, load it here
  (org-roam-bibtex-mode))
#+END_SRC

* Calendar
  Set up syncing with google calendar  following https://github.com/emacsmirror/org-gcal.
  Basic calfw config from https://github.com/kiwanami/emacs-calfw
  #+BEGIN_SRC emacs-lisp
    (use-package calfw
      :init
      (setq cfw:fchar-junction ?╋
	    cfw:fchar-vertical-line ?┃
	    cfw:fchar-horizontal-line ?━
	    cfw:fchar-left-junction ?┣
	    cfw:fchar-right-junction ?┫
	    cfw:fchar-top-junction ?┯
	    cfw:fchar-top-left-corner ?┏
	    cfw:fchar-top-right-corner ?┓
	    calendar-week-start-day 1 ; 0:Sunday, 1:Monday
	    ))
    (use-package calfw-org)
    (use-package calfw-ical)
    (use-package calfw-cal)

  (defun klk/open-calendar ()
    "CFW config for my calendars."
    (interactive)
    (cfw:open-calendar-buffer
     :contents-sources
     (list
      (cfw:org-create-source "DarkGreen")
      (cfw:ical-create-source "gcal" (klk/get-gcal) "Blue")
;      (cfw:ical-create-source "stanford" (klk/stanford-cal) "Red")
     )))
  #+END_SRC

* babel
  #+BEGIN_SRC emacs-lisp
(use-package jupyter
  :config
  (require 'jupyter-julia))

(setq org-src-fontify-natively t
      org-src-tab-acts-natively t
      org-confirm-babel-evaluate nil
      org-edit-src-content-indentation 0)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (jupyter . t)
   (octave . t)
   ;; other languages..
   ))
#+END_SRC
